name: 'deployToReleaseBranch' ## 這支 workflow 的名稱

## 監聽 main 分支若有 push 行為就執行
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest ## 在什麼環境運行
    
    ## 每個 name 就是一個步驟
    steps: 
    - name: Checkout ## 把你的 repository 拉出來
      uses: actions/checkout@v1
    - name : run deployToReleaseBranch.sh ## 初始化專案及執行 deploy.sh
      env: # 設定環境變數
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} ## 設定存取專案用的 ssh-key
      run: sh ./.github/deployToReleaseBranch.sh
